site_name: GraceHub Manual
site_url: https://gracehub.ru/manual/

theme:
  name: material
  custom_dir: docs/overrides        # папка с overrides (overrides/main.html)
  palette:
    # Светлая тема (white / cream / blue)
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Переключить на тёмную тему

    # Тёмная рабочая тема (графитовая)
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Переключить на светлую тему

nav:
  - Обзор: index.md
  - Быстрый старт:
      - Требования: requirements.md
      - Подготовка окружения: setup.md
      - Запуск для разработки: dev-run.md
      - Продакшен-деплой: prod-deploy.md
  - Использование:
      - Общий сценарий: usage-flow.md
  - Архитектура:
      - Стек и структура проекта: architecture.md
  - Логи и мониторинг: logging.md
  - Лицензия: license.md

markdown_extensions:
  - attr_list

extra_css:
  - assets/extra.css

docs_dir: docs
site_dir: site

