services:
  postgres:
    image: postgres:16-alpine
    container_name: gh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gracehub
      POSTGRES_USER: gh_user
      POSTGRES_PASSWORD: ghJh56U65ny567uj65656u6
    ports:
      # Публикуем порт только на localhost хоста
      - "127.0.0.1:5432:5432"
    volumes:
      # Данные Postgres
      - postgres_data:/var/lib/postgresql/data
      # Дополнительные конфиги (01-tuning.conf и пр.)
      - ./postgres/conf.d:/etc/postgresql/conf.d

volumes:
  postgres_data:

